[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.104.1",
    "uvicorn==0.24.0",
    "qdrant-client==1.7.0",
    "openai==1.3.5",
    "pydantic==2.5.0",
    "python-dotenv==1.0.0",
    "mangum==0.17.0",
    "numpy==1.24.3",
    "anyio==4.0.0",
    "starlette==0.27.0"
]
